Rize kari front
Winter-Seminar-Series/WSS-site pull request #175
Opened 2020-12-12 15:51 UTC by AmooHashem

2020-12-12 15:57 UTC, emranbm requested changes

2020-12-12 15:57 UTC, emranbm commented on front/src/redux/actions/urls.tsx
> +    : 'https://cors-anywhere.herokuapp.com/https://sharif-wss.ir/api/';
undo

2020-12-12 15:57 UTC, emranbm commented on front/src/styles/_publicCard.scss
> +    // margin: 1rem;
remove

2020-12-12 15:57 UTC, emranbm commented on front/src/views/Home.tsx
> +                    {/* {startDate ? moment(startDate, "yy-mm-dd").format(`MMMM Do, YYYY`) : ''} */}
Why not using the start and end dates??

2020-12-12 19:00 UTC, AmooHashem commented on front/src/redux/actions/urls.tsx
> +    : 'https://cors-anywhere.herokuapp.com/https://sharif-wss.ir/api/';
قبول دارین اگه بخوام هر تغییری که میدم، برم برای دیدنش پروژه رو بیلد کنم، تا یه هغته دیگه هم سایت نمی‌رسید؟

2020-12-12 19:02 UTC, AmooHashem commented on front/src/styles/_publicCard.scss
> +    // margin: 1rem;
بابا جدا چرا باید کامنتارو پاک کرد؟ یهو فرداش دیدیم خوب نشده، برمی‌گردونیمش یه لحظه.
کامنتِ گنده هم که نکردم.

2020-12-12 19:02 UTC, AmooHashem commented on front/src/views/Home.tsx
> +                    {/* {startDate ? moment(startDate, "yy-mm-dd").format(`MMMM Do, YYYY`) : ''} */}
چون توی چیزای برگشتی از بک، تاریخ پایان نبود هنوز.

2020-12-12 19:10 UTC, emranbm commented on front/src/views/Home.tsx
> +                    {/* {startDate ? moment(startDate, "yy-mm-dd").format(`MMMM Do, YYYY`) : ''} */}
{
    "main_image_url": null,
    "description": "Description",
    "main_clip_url": null,
    "booklet_url": null,
    "staff_count": 37,
    "is_active": true,
    "is_registration_open": false,
    "participants_count": 1,
    "ical_link": null,
    "year": 2020,
    "start_date": "2020-12-31",
    "end_date": "2021-01-03",
    "proposal_link": null,
    "show_stats": true,
    "registration_fee": 40000,
    "calendar_link": null
}

2020-12-12 19:10 UTC, emranbm commented on front/src/views/Home.tsx
> +                    {/* {startDate ? moment(startDate, "yy-mm-dd").format(`MMMM Do, YYYY`) : ''} */}
هست که!

2020-12-12 19:12 UTC, emranbm commented on front/src/redux/actions/urls.tsx
> +    : 'https://cors-anywhere.herokuapp.com/https://sharif-wss.ir/api/';
خب اوکی اینو جداگانه بعدا یادمون باشه برداریم. پرفورمنسش خیلی داغونه این کار

2020-12-13 00:13 UTC, AmooHashem commented on front/src/views/Home.tsx
> +                    {/* {startDate ? moment(startDate, "yy-mm-dd").format(`MMMM Do, YYYY`) : ''} */}
آره اینو اشتباه کردم. :(

2020-12-13 03:42 UTC, emranbm approved these changes

2020-12-13 03:51 UTC, merged