User Profile APIs
Winter-Seminar-Series/WSS-site pull request #40
Opened 2020-11-19 16:53 UTC by ahmadsalimi

2020-11-19 19:04 UTC, emranbm requested changes

2020-11-27 10:21 UTC, ahmadsalimi commented on backend/api/views.py
> +class UserProfileViewSet(viewsets.ViewSet):
I didn't need exactly what `ModelViewSet` provides, I needed customized implementations instead, so I preferred to implement this way.

2020-11-27 10:25 UTC, ahmadsalimi commented on backend/WSS/models.py
> +    name = models.CharField(max_length=250, verbose_name="First Name (in English)")
I removed these fields and now `UserProfile` is using `User.first_name` and `User.last_name`.

2020-11-27 15:22 UTC, emranbm approved these changes

2020-11-27 15:30 UTC, merged