Feature/auth api
Winter-Seminar-Series/WSS-site pull request #58
Opened 2020-11-24 17:26 UTC by AlirezaT99

Initial Authentication API
Using Knox Token Authentication
Won't close #35 ._.

2020-11-24 19:53 UTC, emranbm commented
Nice! :+1:

2020-11-27 15:29 UTC, emranbm requested changes

2020-11-27 15:29 UTC, emranbm commented on backend/WSS/migrations/0010_auto_20201127_1225.py
> +# Generated by Django 3.1.3 on 2020-11-27 12:25
Please set an appropriate file name like `0010_make_userprofile_fields_nullable.py`

2020-11-27 17:21 UTC, emranbm approved these changes

2020-11-28 15:54 UTC, ahmadsalimi approved these changes
Everything seems to be OK 💯

2020-11-28 17:17 UTC, merged